# Generated by Django 6.0.6 on 2026-08-14 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('before', 'Before service'), ('after', 'After service')], default='before', max_length=10)),
                ('angle', models.CharField(choices=[('front', 'Front'), ('front_left', 'Front left'), ('front_right', 'Front right'), ('left', 'Left side'), ('right', 'Right side'), ('rear_left', 'Rear left'), ('rear_right', 'Rear right'), ('rear', 'Rear'), ('roof', 'Roof'), ('interior_front', 'Interior front'), ('interior_rear', 'Interior rear'), ('wheels', 'Wheels / tires'), ('other', 'Other')], max_length=32)),
                ('photo', models.ImageField(upload_to='inspections/%Y/%m/')),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('analysis_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='jobs.job')),
            ],
            options={
                'ordering': ['job_id', 'phase', 'angle', '-created_at'],
                'indexes': [models.Index(fields=['job', 'phase'], name='inspections_job_id_c2bc1f_idx'), models.Index(fields=['analysis_status'], name='inspections_analysi_e086ee_idx')],
            },
        ),
    ]
