# Generated by Django 6.0.6 on 2026-06-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(help_text="User email or 'cron' for scheduled runs.", max_length=120)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('n_samples', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=12)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('artefact_path', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurnScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_at', models.DateTimeField(help_text='The `as_of` timestamp sent to the ML service.')),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('risk_bucket', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=8)),
                ('model_version', models.CharField(help_text="Maps to the bundle's `trained_at` field — lets us trace which trained artefact produced this score.", max_length=64)),
                ('model_name', models.CharField(max_length=64)),
                ('feature_set', models.CharField(max_length=64)),
                ('feature_snapshot', models.JSONField(help_text='Exact feature dict sent to the ML service. Kept so that the matching ChurnLabel can be paired with the features used at score time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_scores', to='users.customer')),
            ],
            options={
                'ordering': ['-scored_at'],
                'indexes': [models.Index(fields=['customer', '-scored_at'], name='analytics_c_custome_9c57fe_idx'), models.Index(fields=['-scored_at'], name='analytics_c_scored__397afc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChurnLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField(help_text='The `as_of` date of the original ChurnScore this label corresponds to.')),
                ('window_days', models.IntegerField(default=180)),
                ('churned', models.BooleanField(help_text='True if the customer had no completed job in [cutoff, cutoff+window_days].')),
                ('feature_snapshot', models.JSONField(help_text='Copy of the features at cutoff time. Used as the training X for retrain runs so that label and features are properly aligned.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_labels', to='users.customer')),
                ('used_in_retrain', models.ForeignKey(blank=True, help_text='The retrain run that first consumed this label, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels_used', to='analytics.retrainrun')),
            ],
            options={
                'ordering': ['-cutoff_date'],
                'indexes': [models.Index(fields=['used_in_retrain'], name='analytics_c_used_in_afb1c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'cutoff_date'), name='uniq_customer_cutoff')],
            },
        ),
    ]
