# Generated by Django 6.0.6 on 2026-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trading_name', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('industry_mode', models.CharField(choices=[('mobile', 'Mobile service'), ('fixed', 'Fixed location')], default='mobile', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=120)),
                ('address_postcode', models.CharField(blank=True, max_length=20)),
                ('address_country', models.CharField(blank=True, max_length=64)),
                ('brand_color', models.CharField(default='#2563EB', max_length=9)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('worker', 'Worker')], default='worker', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['business_id', 'role'],
            },
        ),
    ]
