# Generated by Django 6.0.6 on 2026-09-11 10:22

from django.db import migrations, models


def backfill_existing_member_services(apps, schema_editor):
    """Qualify existing active members for all of their business's current services."""
    Membership = apps.get_model("businesses", "Membership")
    for membership in Membership.objects.filter(status="active", user__isnull=False):
        membership.services.set(membership.business.services.all())


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_indemnitydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='buffer_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='qualified_members', to='businesses.service'),
        ),
        migrations.RunPython(backfill_existing_member_services, noop),
    ]
